# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c02606a79764b0d35248799a5ddee21d9ded92cae042a00667310bf68238fe895b95d5b16afc61eda4db48ff98fa0682a29b697c99c2b635196577e8ea1a267

test:
  secret_key_base: a48d973dd508109ff35a2d8bff5622539c03b3b9a00c976bafa046511cae8fda20012c0d15f0715146d39ab42f3ff766e951430fef0113e021db5f3e39e25810

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
